### ISSUE TITLE
There is no I.startMyActivity() generated if there is no @Extra annotation in the class.

### ISSUE THREAD

**Issue by thubalek** [FrantisekGazo/Blade#1]
Some activities don't have extras but I would like to use I.startMyActivity() pattern for all activities in my project.

Please consider adding some way how to mark activities to be included in I class.

I would prefer to introduce @BladeActivity (and @BladeFragment, @BladeService, ...) for this purpose. Such a annotation could give more fine grained control over code generation.

**Comment by FrantisekGazo** [comment]
There will be one annotation @Blade (at least for now).

So if you do not use any @Arg/@Extra/... annotation inside a class, but you want the library to generate something for this class, then just annotate the class with @Blade, like this:

@Blade
public class A {
} 

And then I plan to create another annotations for advanced setup - e.g. @ArgConfig, @ExtraConfig, ... - which will also annotate whole class. Because if I put everything inside one @Blade annnotation, it would get disorganized, as I add more supported annotation.

What do you think about that?
