### ISSUE TITLE
Multiple annotations

### ISSUE THREAD

**Issue by FrantisekGazo** [FrantisekGazo/Blade#7]
- Add unit tests
- add note to wiki

**Comment by GuyDavis90** [comment]
So the issue with the @Arg + @State is that they are both injected into the same onCreate.
Could a possible solution be to offer as a parameter to the @State to allow the user to decide where the state will be restored?
For Fragments, it can be restored in any of onCreate/onViewCreated/onViewStateRestored?
For Activities, in the onCreate/onRestoreInstanceState/onPostCreate?
They all seem to get the same bundle object so this could be a possibility to weave into one of these functions instead.
Another option would be to force using a Boxed type for Arguments, and if it's not null then don't restore it? (I'm not sure if this is a safe option though, since I don't know 100% if we can safely assume it was restored by the @State).
Thoughts please? :)

**Comment by FrantisekGazo** [comment]
I'll make an adjustment to the blade weaving engine so that `@State` overrides `@Arg`/`@Extra`- that means it will be weaved bellow them.

I was considering that user of this library could customize their priority, but then I realized that it does not make sense for `@Arg` to have higher priority than `@State`.

**Comment by FrantisekGazo** [comment]
@GuyDavis90 I just published `2.2.1-beta4` with implementation of weaving priority. So when you do clean build, `@State` should now always override other annotations in `onCreate()`. Give it a try :)

**Comment by FrantisekGazo** [comment]
**Test Comment:** When I tried to create tests for _Helper classes for classes with multiple annotations I encountered problem with their method order - it was non-deterministic. So I will have make some experiments with testing, because right now I have no way to test it. I can only test whole generated class, not if it contains some method.
So for now I am testing the priorities in already existing tests (for single type of annotation).

**Comment by FrantisekGazo** [comment]
Added note to wiki

**Comment by GuyDavis90** [comment]
I've updated 2 of my projects to use the beta branch and have seen it perform correctly after several clean builds.
On another note, I pulled the repo and tried to build it locally with some changes and it wouldn't work for me with mavenLocal.
Perhaps this is me not doing something correctly? Any ideas why this wouldn't work for me?

**Comment by FrantisekGazo** [comment]
Great.

You need to change version of the library in `gradle.properties` and in `plugin/src/main/groovy/eu/f3rog/blade/plugin/BladePlugin.groovy` also. You have to use different version name that is not published yet.
